/**
 * Shared SEO constants and helpers for consistent metadata across routes.
 *
 * All canonical URLs must be absolute and use the production domain.
 */

export const SITE_URL = "https://crepequer.dev";

/**
 * Build an absolute canonical URL for a given path.
 * The path should start with "/" (e.g. "/blog", "/blog/my-post").
 * For the root path, use "/".
 */
export function canonicalUrl(path: string): string {
  const normalized = path === "/" ? "/" : path.replace(/\/+$/, "");
  return `${SITE_URL}${normalized}`;
}

/**
 * Sitemap entry type for the static sitemap builder helper.
 */
export interface SitemapEntry {
  loc: string;
  lastmod: string;
  changefreq: "always" | "hourly" | "daily" | "weekly" | "monthly" | "yearly" | "never";
  priority: number;
  alternates?: { hreflang: string; href: string }[];
}

/**
 * Known blog post slugs.
 * @deprecated The sitemap is now dynamically generated by `src/routes/sitemap[.]xml.ts`
 * which queries D1. This array is kept only for backward-compat with tests; new code
 * should not reference it.
 */
export const KNOWN_POST_SLUGS: string[] = [];
